version: '3.9'
  
  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Dmm@dmaack4641"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Homolog"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
      #-v /home/felipe/docker/mssql:/var/opt/mssql/data
    networks:
      - app

services:
  TaskManager-Api:
    container_name: TaskManager-Api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app