networks:
  app:
    driver: bridge

volumes:
  sqlvolume:
  seqdata:

services:
  sqlserver:
    container_name: sqlserver-dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Dmm@dmaack4641"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
      #-v /home/felipe/docker/mssql:/var/opt/mssql/data
    networks:
      - app

  container-taskmanager:
    container_name: container-taskmanager-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5048:5048"
      - "7220:7220"
    depends_on:
      - sqlserver
    networks:
      - app
